- name: Install Raspberries
  hosts: raspberries
  #vars_files:
  #  - "{{ vaultfile }}"
  become: yes
  # see inventory for installing what package on what device
  roles:
    - basic
    - motd
    - motion
    - samba
    - deconz
    - nodejs
    - homebridge
    - graphite
    - dnsmasq
    - nginx
