---

# Credits go to https://github.com/rasputnik/ansible-homebridge
- name: install homebridge dependencies
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - libavahi-compat-libdnssd-dev
    - git

- name: install homebridge via npm
  become: yes
  command: npm install -g --unsafe-perm homebridge

- name: add homebridge user
  become: yes
  user:
    name: homebridge
    home: "{{ homebridge_dir }}"
    createhome: yes
    comment: "HomeBridge"

- name: Add user "homebridge" to sudo
  lineinfile:
    path: /etc/sudoers.d/homebridge
    line: 'homebridge ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'

- name: add systemd unit and EnvFile
  become: yes
  template:
    src: ".{{ item }}.j2"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0444
  with_items:
    - "{{ homebridge_defaults }}"
    - /etc/systemd/system/homebridge.service
  notify: restart homebridge

- name: add homebridge config.json
  become: yes
  template:
    src: "./var/lib/homebridge/config.json.j2"
    dest: "/var/lib/homebridge/config.json"
    owner: homebridge
    group: homebridge
    mode: 0444
  notify: restart homebridge

- name: start homebridge
  service:
    name: homebridge
    state: started
    enabled: yes
