---
  
homebridge_dir: "/var/lib/homebridge"
homebridge_bin: "/usr/bin/homebridge"
homebridge_defaults: "/etc/default/homebridge"

homebridge_name: "homebridge"
homebridge_port: "51826"
homebridge_pin: "021-25-152"

homebridge_ui_port: 8080
